name: nextflow_pipeline_env
channels:
  - conda-forge
  - bioconda
  - defaults 
dependencies:
  - nextflow=24.10.6
  - fastqc=0.12.1
  - cutadapt=5.2
  - bwa=0.7.17      
  - samtools=1.20   
  - bcftools=1.20   
  - openjdk=11     
